name: global-storm

channels:
  - conda-forge
  - defaults

dependencies:
  - geopandas=0.12.1
  - jupyter=1.0.0
  - jupyter-black=0.3.1
  - jupytext
  - matplotlib=3.5.2
  - numpy=1.21.5
  - pandas=1.4.4
  - pre-commit=2.20.0
  - seaborn==0.12.1
  - shap=0.40.0
  - scikit-learn=1.1.2
  - statsmodels=0.13.2
  - xgboost==1.5.0
  # The following all come from climada
  - bottleneck>=1.3
  - cartopy>=0.20.0
  - cfgrib>=0.9.7,<0.9.10  # 0.9.10 cannot read the icon_grib files from https://opendata.dwd.de
  - contextily>=1.0,<1.2  # 1.2 has removed the deprecated contextily.sources
  - dask>=2.25
  - gdal!=3.4.1  # has an issue with fiona on Windows (#403)
  # - geopandas>=0.8
  - h5py>=2.10
  - haversine>=2.3
  # - matplotlib>=3.2
  - netcdf4>=1.5
  - numba>=0.51,!=0.55.0  # 0.55.0 has a bug breaking coverage reports
  - openpyxl>=3.0
  - pandas-datareader>=0.9
  - pathos>=0.2
  - pint>=0.15
  - pip
  - proj!=9.0.0  # there are issues with proj 9.0.0 (#381)
  - pycountry>=20.7
  - pyepsg>=0.4
  - pytables>=3.6
  - python=3.8
  - pyxlsb>=1.0
  - rasterio>=1.2.7,<1.3  # 1.3 yields different results for some tests (#512)
  - requests>=2.24
  - salib>=1.3.0
  - scikit-learn>=1.0
  - scipy>=1.6
  # - statsmodels>=0.11
  - tabulate>=0.8
  - tqdm>=4.48
  - xarray>=0.13
  - xlrd>=1.2
  - xlsxwriter>=1.3
  - xmlrunner>=1.7
  - pip:
    - climada==3.2.0
    # - deprecation>=2.1 # climada
    # - overpy>=0.4 # climada
    # - peewee>=3.14 # climada
    # - pybufrkit>=0.2 # climada
    # - SALib==1.3.12 # climada
