import os
from pathlib import Path

import pandas as pd

RS_BASE = 12345


def get_training_dataset():
    # TODO: make this method regenerate the combined dataset
    #  from scratch. For now, just read in the dataset generated by
    #  nobebook 01.
    input_dir = (
        Path(os.getenv("STORM_DATA_DIR")) / "analysis/03_new_model_training"
    )
    filename = input_dir / "new_model_training_dataset.csv"
    return pd.read_csv(filename)
